-- Jalankan file ini di Supabase SQL Editor jika project sudah punya schema lama.
-- Menambahkan tabel feedbacks + unique index badge (selaras SQLite v10).

create table if not exists feedbacks (
  id bigint generated by default as identity primary key,
  "userId" bigint references users(id) on delete set null,
  rating integer not null,
  message text not null,
  category text,
  "createdAt" text not null
);

create unique index if not exists badges_user_badge_unique
  on badges ("userId", "badgeName");

alter table feedbacks enable row level security;

drop policy if exists "edufun public feedbacks" on feedbacks;
create policy "edufun public feedbacks" on feedbacks for all using (true) with check (true);
