-- EduFun Supabase schema.
-- Run this once in Supabase SQL Editor before building the app with:
-- --dart-define=SUPABASE_URL=... --dart-define=SUPABASE_ANON_KEY=...

create table if not exists users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password text not null,
  role text default 'student',
  photo text,
  about text,
  "createdAt" text not null,
  level integer default 1,
  xp integer default 0,
  "isPremium" integer default 0
);

create table if not exists questions (
  id bigint generated by default as identity primary key,
  question text not null,
  options text not null,
  "correctAnswer" text not null,
  category text not null,
  difficulty text not null,
  "imageUrl" text
);

create table if not exists scores (
  id bigint generated by default as identity primary key,
  "userId" bigint not null references users(id) on delete cascade,
  score integer not null,
  "totalQuestions" integer not null,
  category text not null,
  timestamp text not null
);

create table if not exists badges (
  id bigint generated by default as identity primary key,
  "userId" bigint not null references users(id) on delete cascade,
  "badgeName" text not null,
  "badgeIcon" text,
  "unlockedAt" text not null
);

create table if not exists user_locations (
  id bigint generated by default as identity primary key,
  "userId" bigint not null references users(id) on delete cascade,
  "userName" text not null,
  latitude double precision not null,
  longitude double precision not null,
  "locationName" text not null,
  points integer default 0,
  timestamp text not null
);

create table if not exists materials (
  id bigint generated by default as identity primary key,
  "mentorId" bigint not null references users(id) on delete cascade,
  title text not null,
  category text default 'General',
  content text,
  "filePath" text,
  "fileData" text,
  "postTestQuizId" bigint,
  "isExclusive" integer default 0,
  "createdAt" text not null
);

create table if not exists quizzes (
  id bigint generated by default as identity primary key,
  "mentorId" bigint not null references users(id) on delete cascade,
  title text not null,
  type text default 'multiple_choice',
  "materialId" bigint references materials(id) on delete set null,
  "deadlineAt" text,
  "createdAt" text not null
);

create table if not exists user_mentor_follows (
  id bigint generated by default as identity primary key,
  "studentId" bigint not null references users(id) on delete cascade,
  "mentorId" bigint not null references users(id) on delete cascade,
  "followedAt" text not null,
  unique ("studentId", "mentorId")
);

create table if not exists quiz_questions (
  id bigint generated by default as identity primary key,
  "quizId" bigint not null references quizzes(id) on delete cascade,
  "questionText" text not null,
  type text default 'multiple_choice',
  options text not null,
  "correctAnswer" text not null
);

create table if not exists quiz_submissions (
  id bigint generated by default as identity primary key,
  "quizId" bigint not null references quizzes(id) on delete cascade,
  "studentId" bigint not null references users(id) on delete cascade,
  answers text not null,
  score integer not null,
  "submittedAt" text not null
);

alter table users enable row level security;
alter table questions enable row level security;
alter table scores enable row level security;
alter table badges enable row level security;
alter table user_locations enable row level security;
alter table materials enable row level security;
alter table quizzes enable row level security;
alter table user_mentor_follows enable row level security;
alter table quiz_questions enable row level security;
alter table quiz_submissions enable row level security;

drop policy if exists "edufun public users" on users;
drop policy if exists "edufun public questions" on questions;
drop policy if exists "edufun public scores" on scores;
drop policy if exists "edufun public badges" on badges;
drop policy if exists "edufun public user_locations" on user_locations;
drop policy if exists "edufun public materials" on materials;
drop policy if exists "edufun public quizzes" on quizzes;
drop policy if exists "edufun public user_mentor_follows" on user_mentor_follows;
drop policy if exists "edufun public quiz_questions" on quiz_questions;
drop policy if exists "edufun public quiz_submissions" on quiz_submissions;

create policy "edufun public users" on users for all using (true) with check (true);
create policy "edufun public questions" on questions for all using (true) with check (true);
create policy "edufun public scores" on scores for all using (true) with check (true);
create policy "edufun public badges" on badges for all using (true) with check (true);
create policy "edufun public user_locations" on user_locations for all using (true) with check (true);
create policy "edufun public materials" on materials for all using (true) with check (true);
create policy "edufun public quizzes" on quizzes for all using (true) with check (true);
create policy "edufun public user_mentor_follows" on user_mentor_follows for all using (true) with check (true);
create policy "edufun public quiz_questions" on quiz_questions for all using (true) with check (true);
create policy "edufun public quiz_submissions" on quiz_submissions for all using (true) with check (true);
